<a href="https://colab.research.google.com/github/nihal0619/Neural-Network-/blob/main/kohonen_and_hopfield.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

kohonen

In [7]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, f1_score, accuracy_score

In [8]:
weights = np.random.rand(2, 4)
print(weights)
input_vector = np.array([1, 2, 3, 4])
print(weights - input_vector)

[[0.55542363 0.35518627 0.262173   0.44045003]
 [0.92548032 0.66474799 0.26212809 0.65308512]]
[[-0.44457637 -1.64481373 -2.737827   -3.55954997]
 [-0.07451968 -1.33525201 -2.73787191 -3.34691488]]


In [9]:
class KSOFM:
    def __init__(self, num_input, num_output, learning_rate=0.1, epochs=100):
        self.num_input = num_input
        self.num_output = num_output
        self.learning_rate = learning_rate
        self.weights = np.random.rand(num_output, num_input)
        # self.weights = np.array([
        #     [0.3, 0.5, 0.7, 0.2],
        #     [0.6, 0.7, 0.4, 0.3]
        # ])
        self.epochs = epochs

    def train(self, X):
        for i in range(self.epochs):
            for _, x in enumerate(X):
                # print(x)
                # print(self.weights)
                # Calculate the distance between the input vector and each weight vector
                distances = np.linalg.norm(self.weights - x, axis=1)
                # print(distances)
                # Find the index of the winning neuron
                winner = np.argmin(distances)
                # Update the weights of the winning neuron
                self.weights[winner] += self.learning_rate * (x - self.weights[winner])
                # print(f'Epoch {i+1}, Input {x}, Winner {winner}, Weights {self.weights}')
            print(f'Epoch {i+1}, Weights {self.weights}')
        return self.weights

    def predict(self, X):
        y_pred = []
        for _, x in enumerate(X):
            distances = np.linalg.norm(self.weights - x, axis=1)
            winner = np.argmin(distances)
            y_pred.append(winner)
        return y_pred

In [10]:
X = np.array([[1, 0, 1, 0], [1, 0, 0, 0], [1, 1, 1, 1], [0, 1, 1, 0]])
ksofm = KSOFM(4, 2, learning_rate=0.6, epochs=10)
w = ksofm.train(X)
#print(w)

Epoch 1, Weights [[0.26845011 0.84422326 0.90196618 0.36360728]
 [0.8733712  0.10877073 0.37214651 0.04354494]]
Epoch 2, Weights [[0.28295202 0.97507572 0.98431459 0.29817716]
 [0.97973939 0.01740332 0.29954344 0.00696719]]
Epoch 3, Weights [[0.28527232 0.99601212 0.99749033 0.28770835]
 [0.9967583  0.00278453 0.28792695 0.00111475]]
Epoch 4, Weights [[2.85643572e-01 9.99361938e-01 9.99598453e-01 2.86033335e-01]
 [9.99481328e-01 4.45524903e-04 2.86068312e-01 1.78360056e-04]]
Epoch 5, Weights [[2.85702971e-01 9.99897910e-01 9.99935753e-01 2.85765334e-01]
 [9.99917013e-01 7.12839844e-05 2.85770930e-01 2.85376089e-05]]
Epoch 6, Weights [[2.85712475e-01 9.99983666e-01 9.99989720e-01 2.85722453e-01]
 [9.99986722e-01 1.14054375e-05 2.85723349e-01 4.56601743e-06]]
Epoch 7, Weights [[2.85713996e-01 9.99997387e-01 9.99998355e-01 2.85715593e-01]
 [9.99997876e-01 1.82487000e-06 2.85715736e-01 7.30562789e-07]]
Epoch 8, Weights [[2.85714239e-01 9.99999582e-01 9.99999737e-01 2.85714495e-01]
 [9.9999

In [11]:
df = pd.read_csv('/content/sample_data/breast-cancer-wisconsin-data_data.csv')
df['diagnosis'].replace('M', 1, inplace=True)
df['diagnosis'].replace('B', 0, inplace=True)

X = df.iloc[:, 2:32]
y = df.iloc[:, 1]
X = np.array(X)
y = np.array(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [12]:
ksofm = KSOFM(30, 2, learning_rate=0.1, epochs=3000)
w = ksofm.train(X_train)
pred = ksofm.predict(X_test)
print(pred)
print(y_test)
acc = accuracy_score(y_test, pred)
print(acc)

Streaming output truncated to the last 5000 lines.
  1.33959650e-01 2.50977011e-01 2.24266247e-01 8.67132330e-02
  3.13099993e-01 8.68751595e-02]]
Epoch 2689, Weights [[1.92015111e+01 2.11824988e+01 1.25840504e+02 1.15334538e+03
  9.39648405e-02 1.20412190e-01 1.39384322e-01 8.42431709e-02
  1.84868150e-01 5.78099764e-02 6.75282128e-01 1.14118686e+00
  4.68413296e+00 8.31751120e+01 6.42001577e-03 3.02445800e-02
  4.01655958e-02 1.51270314e-02 1.92888911e-02 3.79811756e-03
  2.29410198e+01 2.69225083e+01 1.51782024e+02 1.62892170e+03
  1.27762028e-01 2.84133221e-01 3.68251551e-01 1.65391550e-01
  2.84557982e-01 8.01031474e-02]
 [1.20042989e+01 1.71256440e+01 7.72876619e+01 4.56060492e+02
  9.36283162e-02 8.81109023e-02 5.54050383e-02 2.91933510e-02
  1.78494886e-01 6.40243890e-02 2.56696401e-01 1.11063046e+00
  1.83710464e+00 1.97362611e+01 7.00667019e-03 2.77889144e-02
  2.87564977e-02 9.15650793e-03 2.31004885e-02 4.03705856e-03
  1.34379015e+01 2.36376236e+01 8.80980366e+01 5.6862672

hopfield

In [13]:
import numpy as np
class HopfieldNetwork:
    def __init__(self, n):
        self.n = n
        self.weights = []
        self.threshold = 0

    def fit(self, X):
        self.weights = np.zeros((self.n, self.n))
        for x in X:
            self.weights += np.outer(x, x)
            print(self.weights)
        # self.weights /= self.n
        np.fill_diagonal(self.weights, 0)
        self.threshold = 0

    def predict(self, x):
        y = np.dot(self.weights, x) - self.threshold
        y[y >= 0] = 1
        y[y < 0] = -1
        return y
from random import randint
X = np.array([[1, -1, 1, -1, 1, 1, -1, 1],
              [1, 1, 1, -1, -1, -1, 1, 1]])
hn = HopfieldNetwork(8)
hn.fit(X)
pred = hn.predict([1, -1, 1, 0, 1, 1, -1, 0])
print(f'predicted pattern: {pred}')

[[ 1. -1.  1. -1.  1.  1. -1.  1.]
 [-1.  1. -1.  1. -1. -1.  1. -1.]
 [ 1. -1.  1. -1.  1.  1. -1.  1.]
 [-1.  1. -1.  1. -1. -1.  1. -1.]
 [ 1. -1.  1. -1.  1.  1. -1.  1.]
 [ 1. -1.  1. -1.  1.  1. -1.  1.]
 [-1.  1. -1.  1. -1. -1.  1. -1.]
 [ 1. -1.  1. -1.  1.  1. -1.  1.]]
[[ 2.  0.  2. -2.  0.  0.  0.  2.]
 [ 0.  2.  0.  0. -2. -2.  2.  0.]
 [ 2.  0.  2. -2.  0.  0.  0.  2.]
 [-2.  0. -2.  2.  0.  0.  0. -2.]
 [ 0. -2.  0.  0.  2.  2. -2.  0.]
 [ 0. -2.  0.  0.  2.  2. -2.  0.]
 [ 0.  2.  0.  0. -2. -2.  2.  0.]
 [ 2.  0.  2. -2.  0.  0.  0.  2.]]
predicted pattern: [ 1. -1.  1. -1.  1.  1. -1.  1.]
